package hello.model;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "users")
public class User {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id. Thanks to @ID and .AUTO there will be one and only one  id for each user
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long user_Id;
  
  // The user's email
  @NotNull
  private String email;
  
  // The user's name
  @NotNull
  private String name;

 


  // ------------------------
  // PUBLIC FIELDS
  // ------------------------
  
  public User() { }

  public User(long userId) { 
    this.user_Id = userId;
  }
  public User(String name) {
	  this.name = name; 
  }
  
  public User(String email, String name) {
    this.email = email;
    this.name = name;
  }
  

  // Getter and setter methods

  public long getId() {
    return user_Id;
  }

  public void setId(long value) {
    this.user_Id = value;
  }

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }

  /**
public long getPhone() {
	return phone;
}

public void setPhone(long phone) {
	this.phone = phone;
}

public Date getBirthday() {
	return birthday;
}

public void setBirthday(Date birthday) {
	this.birthday = birthday;
}

public Timestamp getLastchange() {
	return lastchange;
}

public void setLastchange(Timestamp Lastchange) {
	lastchange = Lastchange;
}

public String getLanguage() {
	return language;
}

public void setLanguage(String Language) {
	language = Language;
} */
  
}